# Generated by Django 5.0.6 on 2024-05-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usage',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
